### ISSUE TITLE
Getting KeyError when running DeviceFirmwareSimpleUpdateREDFISH.py

### ISSUE THREAD

**Issue by rdbreak** [dell/iDRAC-Redfish-Scripting#138]
```
❯ python DeviceFirmwareSimpleUpdateREDFISH.py -l ~/Downloads -f BIOS_RTWM9_WN64_2.6.4.EXE

- WARNING, checking server status
Traceback (most recent call last):
  File "DeviceFirmwareSimpleUpdateREDFISH.py", line 459, in <module>
    get_remote_service_api_status()
  File "DeviceFirmwareSimpleUpdateREDFISH.py", line 416, in get_remote_service_api_status
    major_number = data['FirmwareVersion'].split(".")[0]
KeyError: 'FirmwareVersion'
```

The only modification I made to the script was hardcoding the ip, username, and password as variables for testing. I also tried  a newer version of the iDRAC firmware but got the same error.

**Comment by rdbreak** [comment]
I'm trying to run this locally to manage remote Dell hosts. I'm not sure if the script is uploading that file I'm specifying or not.

**Comment by rdbreak** [comment]
Got it figured out.
